### PR TITLE
changed events page

### PR DESCRIPTION
**Pull request by rahilsmd**
eventspage

### CODE REVIEW

**Comment by ananyo2012** [comment]
@rahilsmd Ok this looks fine. But the extra space in left and right of the images isn't looking good. I would suggest increasing the poster widths as they will be larger. Also did you think how to arrange any horizontal posters if any?

**Comment by ananyo2012** [comment]
Also we need to categorise events into some categories. @ghoshbishakh Did you make something like this in the festcms?

**Comment by ananyo2012** [comment]
@rahilsmd Why did you remove the settings.py.example? It is needed to setup the application and is included in the [readme](https://github.com/ghoshbishakh/festcms#deployment)

**Comment by ananyo2012** [comment]
Ok the spacing seems ok in my browser

**Comment by ghoshbishakh** [comment]
@rahilsmd please bring back the settings.py.example

**Comment by ghoshbishakh** [comment]
LGTM. Great job @rahilsmd

**Pull request merged**
