### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by ananyo2012**
Readme changes

@ghoshbishakh Review Please

### CODE REVIEW

**Comment by ananyo2012** [comment]
@ghoshbishakh The secret key needs a non empty value otherwise it throws an error. So I have set it to an arbitrary value. Well I got a warning that we shouldn't keep production secrets in this file. So should I perhaps remove it and add a step to add it in readme or can we safely ignore it since it is just a sampe value?

**Comment by ghoshbishakh** [comment]
keeping it as a step in readme will make everyone aware of the secret key and how it needs to be kept secret. Add it in the readme.

**Comment by ghoshbishakh** [comment]
@ananyo2012 and let the sample key be in the settings. no problem. just add it as a step in readme.

**Comment by ananyo2012** [comment]
@ghoshbishakh Updated. Please review.

**Pull request merged**
