### PR TITLE
changes to css, html files new design

### PR DESCRIPTION
**Pull request by rahilsmd**
please add the links to the pages .

### CODE REVIEW

**Comment by ananyo2012** [comment]
@rahilsmd Please add some screenshots of the pages so that it will be easier to review this PR.

**Comment by ghoshbishakh** [comment]
@ananyo2012 @rahilsmd let us try to move forward quickly. I am merging this one asap and making changes to fit in the backend myself.

**Comment by ghoshbishakh** [comment]
@rahilsmd you could have been more careful about the static tags. Instead of using the {% static %} tags everywhere you have mixed up the /static/.... links and the {% static %} tags. 

Anyway I wanted a uniform navbar for a reason so that it can be easily integrated in each page. Now we have a ton of different css files and js files that are an extra burden in bandwidth and do not add much to the look of the site.

**Comment by ghoshbishakh** [comment]
@rahilsmd Instead of using all assets locally you have created a mix of local assets in static folders and some from cdns. Any reason for that?

**Comment by ghoshbishakh** [comment]
@rahilsmd copied code makes it a mess rahil. You should have spent some more time writing yours or atleast clean up the mess.

**Comment by rahilsmd** [comment]
As I didn't had net connection for the past few days, I removed the CDN's
and downloaded the files.

**Comment by ghoshbishakh** [comment]
No there are still some cdns that is why I was asking. Let me update your code and then Ill ask you to change all cdns to static.

**Pull request merged**
