### PR TITLE
Changed index page with login modal

### PR DESCRIPTION
**Pull request by rahilsmd**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@rahilsmd currently your changes are irrelevant. Please make a very small PR which just adds bootstrap. Then gradually build the entire template.

Remember that index.html will be your home page

**Comment by rahilsmd** [comment]
Just added links to bootstrap css and js.

**Comment by ghoshbishakh** [comment]
Why have you closed this PR?

**Comment by ghoshbishakh** [comment]
And your commit messages must give me some idea about the changes. Like instead of only 'bootstrap' you could have written 'included bootstrap in index page'

**Comment by ghoshbishakh** [comment]
@rahilsmd why have you closed this PR?

**Pull request closed without merging**
